root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/web"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["node_modules", "tmp", "vendor", "web/static"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "html"]
  kill_delay = "1s"

[screen]
  clear_on_rebuild = true

[misc]
  clean_on_exit = true
